# Generated by Django 5.0.2 on 2025-09-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory_agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="file_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="google_drive_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="google_drive_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_file",
            field=models.BooleanField(default=False),
        ),
    ]
